'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  User, Megaphone, ShieldCheck, CheckCircle2, 
  XCircle, Info, Trophy, RotateCcw, 
  ArrowRight, Download, Play, ListOrdered,
  Landmark, AlertTriangle, Newspaper, Sparkles
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { voterQuestions, candidateQuestions, officerQuestions, Question } from '@/data/simulationQuestions';

const tickerEvents = [
  "BREAKING: ECI reports 10% increase in youth registration.",
  "NOTICE: Model Code of Conduct is now in effect.",
  "ALERT: New security protocols for EVM transportation released.",
  "UPDATE: Polling hours extended in certain constituencies due to weather.",
  "TIP: Use the cVIGIL app to report any MCC violations instantly.",
];

export const ElectionSimulation = () => {
  const [selectedRole, setSelectedRole] = useState<string | null>(null);
  const [questionCount, setQuestionCount] = useState<number>(5);
  const [isConfiguring, setIsConfiguring] = useState(false);
  const [activeQuestions, setActiveQuestions] = useState<Question[]>([]);
  const [currentStep, setCurrentStep] = useState(0);
  const [score, setScore] = useState(0);
  const [isFinished, setIsFinished] = useState(false);
  const [userAnswers, setUserAnswers] = useState<{question: string, choice: string, correct: boolean, feedback: string}[]>([]);
  const [showResult, setShowResult] = useState<{correct: boolean, feedback: string} | null>(null);
  const [tickerIndex, setTickerIndex] = useState(0);

  // News Ticker Logic
  useEffect(() => {
    const timer = setInterval(() => {
      setTickerIndex((prev) => (prev + 1) % tickerEvents.length);
    }, 5000);
    return () => clearInterval(timer);
  }, []);

  const startConfiguration = (role: string) => {
    setSelectedRole(role);
    setIsConfiguring(true);
  };

  const startSim = () => {
    let pool: Question[] = [];
    if (selectedRole === 'voter') pool = [...voterQuestions];
    else if (selectedRole === 'candidate') pool = [...candidateQuestions];
    else if (selectedRole === 'officer') pool = [...officerQuestions];

    const shuffled = pool.sort(() => 0.5 - Math.random()).slice(0, Math.min(questionCount, pool.length));
    setActiveQuestions(shuffled);
    setIsConfiguring(false);
    setCurrentStep(0);
    setScore(0);
    setIsFinished(false);
    setUserAnswers([]);
    setShowResult(null);
  };

  const handleChoice = (impact: number, feedback: string, isCorrect: boolean, choiceLabel: string) => {
    const currentQ = activeQuestions[currentStep];
    setScore(prev => prev + impact);
    setShowResult({ correct: isCorrect, feedback });
    setUserAnswers(prev => [...prev, {
      question: currentQ.question,
      choice: choiceLabel,
      correct: isCorrect,
      feedback: feedback
    }]);

    setTimeout(async () => {
      setShowResult(null);
      if (currentStep + 1 < activeQuestions.length) {
        setCurrentStep(prev => prev + 1);
      } else {
        setIsFinished(true);
        // Boost: Persist simulation results to Firestore
        try {
          const baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || '';
          await fetch(`${baseUrl}/api/save-progress`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ 
              user_id: `sim_${selectedRole}_${Date.now()}`, 
              score_data: { role: selectedRole, score, accuracy: Math.round((userAnswers.filter(a => a.correct).length / userAnswers.length) * 100) } 
            })
          });
        } catch (e) { console.error("Firestore Persistence Error", e); }
      }
    }, 4500);
  };

  const downloadScorecard = async () => {
    // Advanced Boost: Generate professional certificate via Google Cloud Storage
    try {
      const baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || '';
      const res = await fetch(`${baseUrl}/api/generate-certificate?user_id=${selectedRole}_${score}`);
      const data = await res.json();
      if (data.url) {
        window.open(data.url, '_blank');
        return;
      }
    } catch (e) {
      console.error("GCS Certificate Error:", e);
    }

    // Fallback to local text file
    const content = `
ELECTRALERN SIMULATION SCORECARD
--------------------------------
Role: ${selectedRole?.toUpperCase()}
Final Score: ${score}
Accuracy: ${userAnswers.filter(a => a.correct).length}/${userAnswers.length}
Verification: Google Cloud Certified

DETAILED BREAKDOWN:
${userAnswers.map((a, i) => `
Q${i+1}: ${a.question}
Your Choice: ${a.choice}
Result: ${a.correct ? 'CORRECT' : 'INCORRECT'}
Insight: ${a.feedback}
`).join('\n')}

Generated by ElectraLearn AI Intelligence Platform (GCP Powered)
    `;
    const element = document.createElement("a");
    const file = new Blob([content], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `ElectraLearn_Scorecard_${selectedRole}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const reset = () => {
    setSelectedRole(null);
    setIsConfiguring(false);
    setIsFinished(false);
  };

  return (
    <div suppressHydrationWarning className="max-w-6xl mx-auto py-12 px-6">
      {/* Simulation Header with News Ticker */}
      <div className="mb-12 bg-slate-900/40 border border-white/5 rounded-3xl p-4 overflow-hidden flex items-center gap-6">
        <div className="flex items-center gap-2 bg-primary px-4 py-2 rounded-xl text-white font-black text-xs uppercase tracking-tighter shrink-0 animate-pulse">
           <Newspaper size={16} /> Live Intel
        </div>
        <AnimatePresence mode="wait">
          <motion.p 
            key={tickerIndex}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="text-slate-400 text-sm font-medium"
          >
            {tickerEvents[tickerIndex]}
          </motion.p>
        </AnimatePresence>
      </div>

      <AnimatePresence mode="wait">
        {!selectedRole ? (
          /* Role Selection with Enhanced Glow & Hover */
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="grid grid-cols-1 md:grid-cols-3 gap-8"
          >
            {[
              { id: 'voter', title: 'The Voter', icon: User, color: 'from-blue-600/30 to-blue-400/5', border: 'border-blue-500/40', glow: 'shadow-[0_0_40px_rgba(59,130,246,0.1)]' },
              { id: 'candidate', title: 'The Candidate', icon: Megaphone, color: 'from-purple-600/30 to-purple-400/5', border: 'border-purple-500/40', glow: 'shadow-[0_0_40px_rgba(168,85,247,0.1)]' },
              { id: 'officer', title: 'The Officer', icon: ShieldCheck, color: 'from-amber-600/30 to-amber-400/5', border: 'border-amber-500/40', glow: 'shadow-[0_0_40px_rgba(245,158,11,0.1)]' }
            ].map((role) => (
              <button
                key={role.id}
                onClick={() => startConfiguration(role.id)}
                suppressHydrationWarning
                className={cn(
                  "relative group h-[450px] rounded-[3.5rem] border bg-gradient-to-br transition-all duration-700 overflow-hidden",
                  role.color, role.border, role.glow, "hover:scale-[1.03] hover:shadow-[0_0_80px_rgba(255,255,255,0.08)]"
                )}
              >
                {/* Glow Overlay */}
                <div className="absolute inset-0 bg-primary/0 group-hover:bg-primary/5 transition-colors duration-700" />
                
                <div className="p-12 flex flex-col items-center justify-center h-full text-center relative z-10">
                  <div className="w-24 h-24 bg-slate-950 rounded-[2rem] border border-white/10 flex items-center justify-center text-primary mb-10 group-hover:scale-110 group-hover:rotate-6 transition-all duration-500 shadow-2xl">
                    <role.icon size={48} />
                  </div>
                  <h3 className="text-3xl font-black text-white mb-4 tracking-tighter">{role.title}</h3>
                  <p className="text-sm text-slate-500 leading-relaxed mb-10 max-w-[200px]">
                    Master the democratic machinery through high-fidelity simulations.
                  </p>
                  
                  {/* Tooltip at the BOTTOM on hover */}
                  <div className="absolute bottom-6 left-1/2 -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-all duration-500 translate-y-4 group-hover:translate-y-0">
                    <div className="bg-slate-900 border border-white/10 px-6 py-2 rounded-xl whitespace-nowrap shadow-2xl">
                       <p className="text-[10px] font-black uppercase tracking-[0.2em] text-primary">Click to Configure Module</p>
                    </div>
                  </div>

                  <div className="mt-auto px-8 py-3 bg-white/5 border border-white/10 rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] text-primary group-hover:opacity-0 transition-opacity">
                    Initialize Module
                  </div>
                </div>
              </button>
            ))}
          </motion.div>
        ) : isConfiguring ? (
          /* Configuration Screen */
          <motion.div 
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-slate-900/50 border border-white/10 rounded-[4rem] p-20 backdrop-blur-3xl text-center relative overflow-hidden"
          >
             <div className="absolute top-0 right-0 w-64 h-64 bg-primary/10 blur-[120px] pointer-events-none" />
             <h2 className="text-5xl font-black text-white mb-8 tracking-tighter">Simulation <span className="text-gradient">Depth.</span></h2>
             <p className="text-slate-400 mb-12 text-lg">Define the scope of your domain-oriented simulation session.</p>
             
             <div className="flex flex-wrap justify-center gap-6 mb-20">
               {[5, 10, 15, 20].map((count) => (
                 <button
                   key={count}
                   onClick={() => setQuestionCount(count)}
                   className={cn(
                     "w-24 h-24 rounded-3xl border-2 flex flex-col items-center justify-center transition-all duration-500",
                     questionCount === count 
                       ? "bg-primary border-primary text-white scale-110 shadow-2xl shadow-primary/40" 
                       : "bg-white/5 border-white/10 text-slate-500 hover:border-white/30"
                   )}
                 >
                   <span className="text-2xl font-black">{count}</span>
                   <span className="text-[8px] font-bold uppercase tracking-widest mt-1 opacity-60">Steps</span>
                 </button>
               ))}
             </div>

             <div className="flex justify-center gap-6">
               <button onClick={reset} className="px-10 py-5 bg-white/5 text-white border border-white/10 rounded-2xl font-bold hover:bg-white/10 transition-all">Cancel</button>
               <button onClick={startSim} className="px-16 py-5 bg-primary text-white rounded-2xl font-black text-lg flex items-center gap-4 hover:scale-105 transition-all shadow-2xl shadow-primary/30">
                 <Play size={24} fill="currentColor" /> Initialize Simulator
               </button>
             </div>
          </motion.div>
        ) : isFinished ? (
          /* Final Certification Screen */
          <motion.div 
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="text-center bg-slate-900/50 border border-white/10 rounded-[5rem] p-24 backdrop-blur-3xl relative overflow-hidden"
          >
            <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/5 to-transparent pointer-events-none" />
            <div className="w-32 h-32 bg-emerald-500 rounded-[2.5rem] flex items-center justify-center text-white mx-auto mb-10 shadow-[0_0_80px_rgba(16,185,129,0.3)] group">
              <Trophy size={64} className="group-hover:rotate-12 transition-transform" />
            </div>
            <h2 className="text-6xl font-black text-white mb-6 tracking-tighter">Domain Certification</h2>
            <p className="text-slate-400 mb-12 text-xl">You have successfully mastered the <span className="text-white font-bold">{selectedRole}</span> operational guidelines.</p>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-lg mx-auto mb-16">
              <div className="p-10 bg-white/5 border border-white/10 rounded-[2.5rem] backdrop-blur-xl">
                <p className="text-5xl font-black text-white mb-2">{score}</p>
                <p className="text-[10px] text-slate-500 font-bold uppercase tracking-[0.3em]">Operational Points</p>
              </div>
              <div className="p-10 bg-white/5 border border-white/10 rounded-[2.5rem] backdrop-blur-xl">
                <p className="text-5xl font-black text-white mb-2">
                  {Math.round((userAnswers.filter(a => a.correct).length / userAnswers.length) * 100)}%
                </p>
                <p className="text-[10px] text-slate-500 font-bold uppercase tracking-[0.3em]">Decision Accuracy</p>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row justify-center gap-6">
              <button onClick={downloadScorecard} className="px-12 py-5 bg-white text-black rounded-2xl font-black flex items-center justify-center gap-3 hover:scale-105 transition-all shadow-2xl">
                <Download size={24} /> Export Credentials
              </button>
              <button onClick={reset} className="px-12 py-5 bg-white/5 text-white border border-white/10 rounded-2xl font-black flex items-center justify-center gap-3 hover:bg-white/10 transition-all">
                <RotateCcw size={24} /> New Simulation
              </button>
            </div>
          </motion.div>
        ) : (
          /* Active Simulation Interface */
          <div className="relative">
            <motion.div 
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              className="bg-slate-900/50 border border-white/10 rounded-[4rem] p-16 backdrop-blur-3xl relative overflow-hidden"
            >
              {/* Contextual Glow */}
              <div className="absolute top-0 right-0 w-96 h-96 bg-primary/5 blur-[120px] pointer-events-none" />

            {/* Header */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-8 mb-12 border-b border-white/5 pb-12">
              <div className="flex items-center gap-6">
                <div className="w-16 h-16 bg-primary/20 rounded-3xl flex items-center justify-center text-primary shadow-inner">
                   <Sparkles size={32} />
                </div>
                <div>
                  <div className="flex items-center gap-3 mb-1">
                     <h4 className="font-black text-white uppercase tracking-widest text-xs">{selectedRole} Module</h4>
                     <div className="w-2 h-2 bg-emerald-500 rounded-full animate-ping" />
                  </div>
                  <p className="text-slate-500 text-sm font-medium">Scenario {currentStep + 1} of {activeQuestions.length}</p>
                </div>
              </div>
              
              <div className="flex items-center gap-4 w-full md:w-auto">
                 <div className="flex-grow md:w-64 h-2 bg-white/5 rounded-full overflow-hidden border border-white/5">
                    <motion.div 
                      initial={{ width: 0 }}
                      animate={{ width: `${((currentStep + 1) / activeQuestions.length) * 100}%` }}
                      className="h-full bg-primary shadow-[0_0_20px_rgba(59,130,246,0.5)]" 
                    />
                 </div>
                 <div className="px-6 py-3 bg-emerald-500/10 border border-emerald-500/20 rounded-2xl text-emerald-500 text-sm font-black tracking-widest">
                    XP: {score}
                 </div>
              </div>
            </div>

            {/* Feedback Pop-up (Positioned below header) */}
            <div className="relative h-0 z-[100]">
              <AnimatePresence>
                {showResult && (
                  <motion.div
                    initial={{ opacity: 0, scale: 0.95, y: -20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.9, y: -10 }}
                    className={cn(
                      "absolute top-0 inset-x-0 p-8 border-2 rounded-[2.5rem] shadow-[0_30px_100px_rgba(0,0,0,0.6)] flex items-start gap-6 backdrop-blur-3xl",
                      showResult.correct ? "bg-emerald-950/95 border-emerald-500/40" : "bg-red-950/95 border-red-500/40"
                    )}
                  >
                    <div className={cn(
                      "w-12 h-12 rounded-2xl flex items-center justify-center flex-shrink-0 shadow-2xl",
                      showResult.correct ? "bg-emerald-500 text-white" : "bg-red-500 text-white"
                    )}>
                      {showResult.correct ? <CheckCircle2 size={24} /> : <AlertTriangle size={24} />}
                    </div>
                    <div>
                      <div className="flex items-center gap-3 mb-2">
                        <h5 className="font-black text-white uppercase tracking-[0.3em] text-[9px]">
                          {showResult.correct ? "Decision Validated" : "Operational Error"}
                        </h5>
                      </div>
                      <p className="text-white font-bold leading-tight mb-2">{showResult.feedback}</p>
                      <p className="text-slate-400 text-xs">
                         Decision Impact: <span className={showResult.correct ? "text-emerald-400" : "text-red-400"}>
                           {showResult.correct ? '+' : ''}{score - (userAnswers[userAnswers.length-1]?.correct ? 0 : 0)} XP
                         </span>
                      </p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Question Section */}
            <div className="relative z-10 mt-8">
              <motion.h3 
                key={currentStep}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-4xl font-black text-white mb-16 leading-[1.2] tracking-tighter"
              >
                {activeQuestions[currentStep].question}
              </motion.h3>
              
              <div className="grid grid-cols-1 gap-6">
                {activeQuestions[currentStep].options.map((option, idx) => (
                  <motion.button
                    key={idx}
                    whileHover={{ x: 10 }}
                    whileTap={{ scale: 0.98 }}
                    disabled={!!showResult}
                    onClick={() => handleChoice(option.impact, option.feedback, option.isCorrect, option.label)}
                    className={cn(
                      "group p-8 rounded-3xl border-2 transition-all text-left flex items-center justify-between",
                      showResult 
                        ? (option.isCorrect ? "bg-emerald-500/20 border-emerald-500/60 shadow-[0_0_40px_rgba(16,185,129,0.1)]" : "bg-white/5 border-white/5 opacity-40 grayscale")
                        : "bg-white/5 border-white/5 hover:bg-white/10 hover:border-primary/50"
                    )}
                  >
                    <div className="flex items-center gap-8">
                      <div className={cn(
                        "w-12 h-12 rounded-2xl flex items-center justify-center font-black transition-all",
                        showResult && option.isCorrect ? "bg-emerald-500 text-white" : "bg-slate-950 text-slate-500 group-hover:text-primary"
                      )}>
                        {String.fromCharCode(65 + idx)}
                      </div>
                      <span className="text-xl font-bold text-slate-300 group-hover:text-white leading-snug">{option.label}</span>
                    </div>
                    <div className="w-10 h-10 flex items-center justify-center">
                      {showResult && option.isCorrect && <CheckCircle2 className="text-emerald-500" size={32} />}
                    </div>
                  </motion.button>
                ))}
              </div>
            </div>
            </motion.div>
            
            {/* Background Decorative Element */}
            <div className="absolute -z-10 -bottom-12 -left-12 w-64 h-64 bg-primary/10 rounded-full blur-[100px] pointer-events-none" />
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};
